### ISSUE TITLE
support `OFFSET <x> <y>` command

### ISSUE THREAD

**Issue by noerw** [sbernauer/breakwater#2]
While not a core command, this can be quite handy for some patterns.
Ref [Shoreline docs](https://github.com/TobleMiner/shoreline#supported-pixelflut-commands):
```
OFFSET <x> <y>               # Apply offset (x,y) to all further pixel draws on this connection
```

Grüße vom Tisch nebenan :heart:

**Comment by sbernauer** [comment]
Should work now. I will roll it out for GPN now, please give me feedback if it works for you - thanks!
Liebe Grüße zurück :)

**Comment by sbernauer** [comment]
This should work now, thanks for your suggestion!
