### ISSUE TITLE
Failed to memadvise buffer to kernel

### ISSUE THREAD

**Issue by robinchrist** [sbernauer/breakwater#28]
```
[2024-06-01T17:19:35Z ERROR breakwater::server] Failed to memadvise buffer to kernel, propably having some performance degration: InvalidRange
[2024-06-01T17:19:35Z ERROR breakwater::server] Failed to memadvise buffer to kernel, propably having some performance degration: NullAddress
```
sbernauer/breakwater@bbef8cf7ce15d6eedcc61382dae06093ab65352d

**Comment by sbernauer** [comment]
Thanks for reporting this!

I now had the time to look into this issue and I'm a bit confused how this can fail, as we allocate the memory directly [above](https://github.com/sbernauer/breakwater/blob/12d799a13d3406bbb1619751d43faddc258130d9/breakwater/src/server.rs#L157), so I don't see any reason the pointer should be invalid or even `null`.

However, the error is only printed and the thread continues processing the data send. The worst thing that *should* happen is a minimal performance degradation.

I don't see how this situation can be improved in any way, would you be ok with closing this for now?

**Comment by robinchrist** [comment]
Yep sure, thanks for looking into it.
Just something we noticed while running Pixelflut with > 100Gbit/s continuous (real world performance) at GPN22.

Maybe it should be noted in the README that this is known?

**Comment by sbernauer** [comment]
Sure, raised a PR for that, happy about review! https://github.com/sbernauer/breakwater/pull/29
