### ISSUE TITLE
Containerimage not available on dockerhub

### ISSUE THREAD

**Issue by rubenhoenle** [sbernauer/breakwater#39]
Hey, this project looked very promising for my use case, so I wanted to try it out. :smile: 

I just noticed that the containerimage for the `0.16.0` version you are using in your docker compose example is not available on docker.io

see https://github.com/sbernauer/breakwater/blob/main/docker/docker-compose.yml#L4
and https://hub.docker.com/r/sbernauer/breakwater/tags

**Comment by rubenhoenle** [comment]
Ok i see, looks like the release pipeline failed: https://github.com/sbernauer/breakwater/actions/runs/10448536105/job/28929167547

**Comment by sbernauer** [comment]
Many thanks for pointing this out and fixing it! I published 0.16.1, this time also on Docker Hub :)
